FROM maven:amazoncorretto
WORKDIR /pricing-service
COPY ./ ./
RUN mvn clean install

FROM amazoncorretto:11
WORKDIR /pricing-service
COPY --from=0 /pricing-service/target/pricing-service-0.0.1-SNAPSHOT.jar ./
CMD ["java","-jar", "pricing-service-0.0.1-SNAPSHOT.jar"]